FROM --platform=${TARGETPLATFORM} redis:6.2.4-buster as build_bloom
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt update -y && apt install -y --no-install-recommends build-essential libcurl4-openssl-dev git && rm -rf /var/lib/apt/lists/*
WORKDIR /build
RUN git clone -b v2.2.4 https://github.com/RedisBloom/RedisBloom.git
WORKDIR /build/RedisBloom
# RUN git submodule update --init --recursive
# RUN make fetch
RUN make

FROM --platform=${TARGETPLATFORM} redis:6.2.4-buster as build
# COPY ./cell/${TARGETPLATFORM}/ /plugins/redis-cell/
COPY ./cell/linux/amd64/ /plugins/redis-cell/
COPY --from=build_bloom /build/RedisBloom/redisbloom.so /plugins/redis-bloom/redisbloom.so
CMD [ "redis-server", "--loadmodule",  "/plugins/redis-cell/libredis_cell.so","--loadmodule","/plugins/redis-bloom/redisbloom.so"  ]